export const compressium = {
    cobblestone: {
        x1: 'compressium:cobblestone_1',
        x2: 'compressium:cobblestone_2',
        x3: 'compressium:cobblestone_3',
        x4: 'compressium:cobblestone_4',
        x5: 'compressium:cobblestone_5',
        x6: 'compressium:cobblestone_6',
        x7: 'compressium:cobblestone_7',
        x8: 'compressium:cobblestone_8',
        x9: 'compressium:cobblestone_9',
    },
    gold: {
        x1: 'compressium:gold_1',
        x2: 'compressium:gold_2',
        x3: 'compressium:gold_3',
        x4: 'compressium:gold_4',
        x5: 'compressium:gold_5',
        x6: 'compressium:gold_6',
        x7: 'compressium:gold_7',
        x8: 'compressium:gold_8',
        x9: 'compressium:gold_9',
    },
    redstone: {
        x1: 'compressium:redstone_1',
        x2: 'compressium:redstone_2',
        x3: 'compressium:redstone_3',
        x4: 'compressium:redstone_4',
        x5: 'compressium:redstone_5',
        x6: 'compressium:redstone_6',
        x7: 'compressium:redstone_7',
        x8: 'compressium:redstone_8',
        x9: 'compressium:redstone_9',
    },
    iron: {
        x1: 'compressium:iron_1',
        x2: 'compressium:iron_2',
        x3: 'compressium:iron_3',
        x4: 'compressium:iron_4',
        x5: 'compressium:iron_5',
        x6: 'compressium:iron_6',
        x7: 'compressium:iron_7',
        x8: 'compressium:iron_8',
        x9: 'compressium:iron_9',
    },
    diamond: {
        x1: 'compressium:diamond_1',
        x2: 'compressium:diamond_2',
        x3: 'compressium:diamond_3',
        x4: 'compressium:diamond_4',
        x5: 'compressium:diamond_5',
        x6: 'compressium:diamond_6',
        x7: 'compressium:diamond_7',
        x8: 'compressium:diamond_8',
        x9: 'compressium:diamond_9',
    },
}
