export const publicBlocks = ['blockcarpentry:illusion_block']

export const blacklist = {
    right_click: [
        /storagenetwork:.+/,
        /catalyst_infusion_table/,
        /vault_diffuser/,
        /tool_vise/,
        /vault_recycler/,
        /vault_artisan_station/,
        /vault_forge/,
        /magnet_modification_table/,
        /vault_charm_controller/,
        /vault_altar/,
        /cryo_chamber/,
        /button/,
        /chest/,
        /crate/,
        /shulker/,
        /cabinet/,
        /computer/,
        /monitor/,
        /modem/,
        /disk/,
        /cabinet/,
        /drawer/,
        /router/,
        /lever/,
        /pot/,
        /bar_panel/,
        /rsgauges/,
        /thermal/,
        /ars_nouveau/,
        /ars_omega/,
    ],
}
